drop extension if exists "pg_net";


  create table "public"."beats" (
    "id" integer generated by default as identity not null,
    "beat" text not null,
    "beat_short" text,
    "river_order" text,
    "upper_lower" text
      );


alter table "public"."beats" enable row level security;


  create table "public"."catch_returns" (
    "id" integer generated by default as identity not null,
    "member_name" text,
    "catch_date" date,
    "brown_trout" integer,
    "brown_trout_killed" integer,
    "grayling" integer,
    "rainbow_trout" integer,
    "other_species" integer,
    "guest" boolean,
    "beats_id" integer,
    "dnf" boolean default false
      );


alter table "public"."catch_returns" enable row level security;


  create table "public"."catch_returns_staging_table" (
    "id" integer generated by default as identity not null,
    "timestamp" text,
    "rod_name" text,
    "catch_date" date,
    "beat" text,
    "brown_trout_released" integer,
    "grayling" integer,
    "rainbow_trout" integer,
    "other_species" integer,
    "brown_trout_retained" integer,
    "guest" boolean,
    "comments" text,
    "dnf" boolean default false
      );


alter table "public"."catch_returns_staging_table" enable row level security;


  create table "public"."members" (
    "id" integer generated by default as identity not null,
    "cr_name" text,
    "email_address" text,
    "member_name" text,
    "year_of_membership" integer
      );


alter table "public"."members" enable row level security;


  create table "public"."reservation_beats" (
    "id" bigint generated by default as identity not null,
    "beat" text not null,
    "beat_id" bigint
      );


alter table "public"."reservation_beats" enable row level security;


  create table "public"."reservations_confirmed_staging" (
    "id" bigint generated by default as identity not null,
    "date" date not null,
    "resource" text not null,
    "name" text not null,
    "cr_name" text
      );


alter table "public"."reservations_confirmed_staging" enable row level security;


  create table "public"."year_param" (
    "id" integer generated by default as identity not null,
    "target_year" integer,
    "target_start_date" date,
    "target_end_date" date
      );


CREATE UNIQUE INDEX "CatchReturns_pkey" ON public.catch_returns USING btree (id);

CREATE UNIQUE INDEX beats_pkey ON public.beats USING btree (id);

CREATE UNIQUE INDEX catch_returns_staging_table_pkey ON public.catch_returns_staging_table USING btree (id);

CREATE INDEX idx_beat ON public.catch_returns_staging_table USING btree (beat);

CREATE INDEX idx_beats_beat ON public.beats USING btree (beat);

CREATE INDEX idx_beats_river_order ON public.beats USING btree (river_order);

CREATE INDEX idx_beats_upper_lower ON public.beats USING btree (upper_lower);

CREATE INDEX idx_catch_date ON public.catch_returns_staging_table USING btree (catch_date);

CREATE INDEX idx_catch_returns_beats_id ON public.catch_returns USING btree (beats_id);

CREATE INDEX idx_catch_returns_catch_date ON public.catch_returns USING btree (catch_date);

CREATE INDEX idx_catch_returns_guest ON public.catch_returns USING btree (guest);

CREATE INDEX idx_reservation_beats_beat ON public.reservation_beats USING btree (beat);

CREATE INDEX idx_reservations_confirmed_staging_date ON public.reservations_confirmed_staging USING btree (date);

CREATE INDEX idx_reservations_confirmed_staging_resource ON public.reservations_confirmed_staging USING btree (resource);

CREATE INDEX members_cr_name_idx ON public.members USING btree (cr_name);

CREATE INDEX members_cr_name_lower_idx ON public.members USING btree (lower(cr_name));

CREATE UNIQUE INDEX members_pkey ON public.members USING btree (id);

CREATE INDEX members_year_of_membership_idx ON public.members USING btree (year_of_membership);

CREATE UNIQUE INDEX reservation_beats_pkey ON public.reservation_beats USING btree (id);

CREATE UNIQUE INDEX reservations_confirmed_staging_pkey ON public.reservations_confirmed_staging USING btree (id);

CREATE UNIQUE INDEX year_param_pkey ON public.year_param USING btree (id);

alter table "public"."beats" add constraint "beats_pkey" PRIMARY KEY using index "beats_pkey";

alter table "public"."catch_returns" add constraint "CatchReturns_pkey" PRIMARY KEY using index "CatchReturns_pkey";

alter table "public"."catch_returns_staging_table" add constraint "catch_returns_staging_table_pkey" PRIMARY KEY using index "catch_returns_staging_table_pkey";

alter table "public"."members" add constraint "members_pkey" PRIMARY KEY using index "members_pkey";

alter table "public"."reservation_beats" add constraint "reservation_beats_pkey" PRIMARY KEY using index "reservation_beats_pkey";

alter table "public"."reservations_confirmed_staging" add constraint "reservations_confirmed_staging_pkey" PRIMARY KEY using index "reservations_confirmed_staging_pkey";

alter table "public"."year_param" add constraint "year_param_pkey" PRIMARY KEY using index "year_param_pkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
 RETURNS event_trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$
;

create or replace view "public"."table_indexes_non_pk" as  SELECT schemaname AS schema_name,
    tablename AS table_name,
    indexname AS index_name,
    indexdef AS index_definition
   FROM pg_indexes
  WHERE ((schemaname = 'public'::name) AND (NOT (indexname IN ( SELECT pg_constraint.conname
           FROM pg_constraint
          WHERE (pg_constraint.contype = 'p'::"char")))))
  ORDER BY tablename, indexname;


create or replace view "public"."table_policies_overview" as  SELECT schemaname,
    tablename,
    policyname,
    permissive,
    roles,
    cmd,
    qual,
    with_check
   FROM pg_policies
  ORDER BY tablename;


create or replace view "public"."table_rls_overview" as  SELECT pg_class.relname AS table_name,
        CASE
            WHEN (pg_class.relrowsecurity = true) THEN '✅ ENABLED (Locked)'::text
            ELSE '⚠️ DISABLED (Open)'::text
        END AS rls_status
   FROM (pg_class
     JOIN pg_namespace ON ((pg_namespace.oid = pg_class.relnamespace)))
  WHERE ((pg_namespace.nspname = 'public'::name) AND (pg_class.relkind = 'r'::"char"))
  ORDER BY pg_class.relname;


create or replace view "public"."view_reservations_confirmed_staging" as  SELECT rcs.date,
    rcs.cr_name,
    rb.beat_id,
    bt.beat
   FROM ((public.reservations_confirmed_staging rcs
     JOIN public.reservation_beats rb ON ((rb.beat = rcs.resource)))
     JOIN public.beats bt ON ((rb.beat_id = bt.id)))
  ORDER BY rcs.date;


create or replace view "public"."view_catch_returns_missing" as  SELECT date,
    cr_name,
    beat_id,
    beat,
    floor(EXTRACT(day FROM (CURRENT_TIMESTAMP - ((date)::timestamp without time zone)::timestamp with time zone))) AS full_days_elapsed
   FROM public.view_reservations_confirmed_staging vrcs
  WHERE ((date < CURRENT_DATE) AND (NOT (EXISTS ( SELECT 1
           FROM public.catch_returns_staging_table crst
          WHERE ((vrcs.date = crst.catch_date) AND (vrcs.beat = crst.beat) AND (vrcs.cr_name = crst.rod_name))))))
  ORDER BY (floor(EXTRACT(day FROM (CURRENT_TIMESTAMP - ((date)::timestamp without time zone)::timestamp with time zone)))) DESC;


create or replace view "public"."view_missing_cr_age_report" as  
WITH return_stats AS (
    SELECT 
        vrcs.cr_name,
        CURRENT_DATE - vrcs.date AS days_old,
        -- 1 if submitted, 0 if missing
        CASE WHEN crst.rod_name IS NOT NULL THEN 1 ELSE 0 END as was_submitted
    FROM view_reservations_confirmed_staging vrcs
    LEFT JOIN catch_returns_staging_table crst 
        ON vrcs.cr_name = crst.rod_name 
        AND vrcs.date = crst.catch_date
    WHERE vrcs.date < CURRENT_DATE
)
SELECT 
    m.member_name,
    SUM(rs.was_submitted) AS "Returns Submitted",
    --COUNT(CASE WHEN rs.was_submitted = 0 AND rs.days_old <= 7 THEN 1 END) AS "1-7 Days",
    COUNT(CASE WHEN rs.was_submitted = 0 AND rs.days_old > 7 AND rs.days_old <= 14 THEN 1 END) AS "8-14 Days",
    COUNT(CASE WHEN rs.was_submitted = 0 AND rs.days_old > 14 AND rs.days_old <= 21 THEN 1 END) AS "15-21 Days",
    COUNT(CASE WHEN rs.was_submitted = 0 AND rs.days_old > 21 AND rs.days_old <= 28 THEN 1 END) AS "21-28 Days",
    COUNT(CASE WHEN rs.was_submitted = 0 AND rs.days_old > 28 THEN 1 END) AS "28+ Days",
    COUNT(CASE WHEN rs.was_submitted = 0 THEN 1 END) AS "Total Missing"
FROM members m
JOIN return_stats rs ON m.cr_name = rs.cr_name
GROUP BY m.member_name
-- Filter: Only show members where the count of missing returns is greater than 0
HAVING COUNT(CASE WHEN rs.was_submitted = 0 THEN 1 END) > 0
ORDER BY "Total Missing" DESC;

grant delete on table "public"."beats" to "anon";

grant insert on table "public"."beats" to "anon";

grant references on table "public"."beats" to "anon";

grant select on table "public"."beats" to "anon";

grant trigger on table "public"."beats" to "anon";

grant truncate on table "public"."beats" to "anon";

grant update on table "public"."beats" to "anon";

grant delete on table "public"."beats" to "authenticated";

grant insert on table "public"."beats" to "authenticated";

grant references on table "public"."beats" to "authenticated";

grant select on table "public"."beats" to "authenticated";

grant trigger on table "public"."beats" to "authenticated";

grant truncate on table "public"."beats" to "authenticated";

grant update on table "public"."beats" to "authenticated";

grant delete on table "public"."beats" to "service_role";

grant insert on table "public"."beats" to "service_role";

grant references on table "public"."beats" to "service_role";

grant select on table "public"."beats" to "service_role";

grant trigger on table "public"."beats" to "service_role";

grant truncate on table "public"."beats" to "service_role";

grant update on table "public"."beats" to "service_role";

grant delete on table "public"."catch_returns" to "anon";

grant insert on table "public"."catch_returns" to "anon";

grant references on table "public"."catch_returns" to "anon";

grant select on table "public"."catch_returns" to "anon";

grant trigger on table "public"."catch_returns" to "anon";

grant truncate on table "public"."catch_returns" to "anon";

grant update on table "public"."catch_returns" to "anon";

grant delete on table "public"."catch_returns" to "authenticated";

grant insert on table "public"."catch_returns" to "authenticated";

grant references on table "public"."catch_returns" to "authenticated";

grant select on table "public"."catch_returns" to "authenticated";

grant trigger on table "public"."catch_returns" to "authenticated";

grant truncate on table "public"."catch_returns" to "authenticated";

grant update on table "public"."catch_returns" to "authenticated";

grant delete on table "public"."catch_returns" to "service_role";

grant insert on table "public"."catch_returns" to "service_role";

grant references on table "public"."catch_returns" to "service_role";

grant select on table "public"."catch_returns" to "service_role";

grant trigger on table "public"."catch_returns" to "service_role";

grant truncate on table "public"."catch_returns" to "service_role";

grant update on table "public"."catch_returns" to "service_role";

grant delete on table "public"."catch_returns_staging_table" to "anon";

grant insert on table "public"."catch_returns_staging_table" to "anon";

grant references on table "public"."catch_returns_staging_table" to "anon";

grant select on table "public"."catch_returns_staging_table" to "anon";

grant trigger on table "public"."catch_returns_staging_table" to "anon";

grant truncate on table "public"."catch_returns_staging_table" to "anon";

grant update on table "public"."catch_returns_staging_table" to "anon";

grant delete on table "public"."catch_returns_staging_table" to "authenticated";

grant insert on table "public"."catch_returns_staging_table" to "authenticated";

grant references on table "public"."catch_returns_staging_table" to "authenticated";

grant select on table "public"."catch_returns_staging_table" to "authenticated";

grant trigger on table "public"."catch_returns_staging_table" to "authenticated";

grant truncate on table "public"."catch_returns_staging_table" to "authenticated";

grant update on table "public"."catch_returns_staging_table" to "authenticated";

grant delete on table "public"."catch_returns_staging_table" to "service_role";

grant insert on table "public"."catch_returns_staging_table" to "service_role";

grant references on table "public"."catch_returns_staging_table" to "service_role";

grant select on table "public"."catch_returns_staging_table" to "service_role";

grant trigger on table "public"."catch_returns_staging_table" to "service_role";

grant truncate on table "public"."catch_returns_staging_table" to "service_role";

grant update on table "public"."catch_returns_staging_table" to "service_role";

grant delete on table "public"."members" to "anon";

grant insert on table "public"."members" to "anon";

grant references on table "public"."members" to "anon";

grant select on table "public"."members" to "anon";

grant trigger on table "public"."members" to "anon";

grant truncate on table "public"."members" to "anon";

grant update on table "public"."members" to "anon";

grant delete on table "public"."members" to "authenticated";

grant insert on table "public"."members" to "authenticated";

grant references on table "public"."members" to "authenticated";

grant select on table "public"."members" to "authenticated";

grant trigger on table "public"."members" to "authenticated";

grant truncate on table "public"."members" to "authenticated";

grant update on table "public"."members" to "authenticated";

grant delete on table "public"."members" to "service_role";

grant insert on table "public"."members" to "service_role";

grant references on table "public"."members" to "service_role";

grant select on table "public"."members" to "service_role";

grant trigger on table "public"."members" to "service_role";

grant truncate on table "public"."members" to "service_role";

grant update on table "public"."members" to "service_role";

grant delete on table "public"."reservation_beats" to "anon";

grant insert on table "public"."reservation_beats" to "anon";

grant references on table "public"."reservation_beats" to "anon";

grant select on table "public"."reservation_beats" to "anon";

grant trigger on table "public"."reservation_beats" to "anon";

grant truncate on table "public"."reservation_beats" to "anon";

grant update on table "public"."reservation_beats" to "anon";

grant delete on table "public"."reservation_beats" to "authenticated";

grant insert on table "public"."reservation_beats" to "authenticated";

grant references on table "public"."reservation_beats" to "authenticated";

grant select on table "public"."reservation_beats" to "authenticated";

grant trigger on table "public"."reservation_beats" to "authenticated";

grant truncate on table "public"."reservation_beats" to "authenticated";

grant update on table "public"."reservation_beats" to "authenticated";

grant delete on table "public"."reservation_beats" to "service_role";

grant insert on table "public"."reservation_beats" to "service_role";

grant references on table "public"."reservation_beats" to "service_role";

grant select on table "public"."reservation_beats" to "service_role";

grant trigger on table "public"."reservation_beats" to "service_role";

grant truncate on table "public"."reservation_beats" to "service_role";

grant update on table "public"."reservation_beats" to "service_role";

grant delete on table "public"."reservations_confirmed_staging" to "anon";

grant insert on table "public"."reservations_confirmed_staging" to "anon";

grant references on table "public"."reservations_confirmed_staging" to "anon";

grant select on table "public"."reservations_confirmed_staging" to "anon";

grant trigger on table "public"."reservations_confirmed_staging" to "anon";

grant truncate on table "public"."reservations_confirmed_staging" to "anon";

grant update on table "public"."reservations_confirmed_staging" to "anon";

grant delete on table "public"."reservations_confirmed_staging" to "authenticated";

grant insert on table "public"."reservations_confirmed_staging" to "authenticated";

grant references on table "public"."reservations_confirmed_staging" to "authenticated";

grant select on table "public"."reservations_confirmed_staging" to "authenticated";

grant trigger on table "public"."reservations_confirmed_staging" to "authenticated";

grant truncate on table "public"."reservations_confirmed_staging" to "authenticated";

grant update on table "public"."reservations_confirmed_staging" to "authenticated";

grant delete on table "public"."reservations_confirmed_staging" to "service_role";

grant insert on table "public"."reservations_confirmed_staging" to "service_role";

grant references on table "public"."reservations_confirmed_staging" to "service_role";

grant select on table "public"."reservations_confirmed_staging" to "service_role";

grant trigger on table "public"."reservations_confirmed_staging" to "service_role";

grant truncate on table "public"."reservations_confirmed_staging" to "service_role";

grant update on table "public"."reservations_confirmed_staging" to "service_role";

grant delete on table "public"."year_param" to "anon";

grant insert on table "public"."year_param" to "anon";

grant references on table "public"."year_param" to "anon";

grant select on table "public"."year_param" to "anon";

grant trigger on table "public"."year_param" to "anon";

grant truncate on table "public"."year_param" to "anon";

grant update on table "public"."year_param" to "anon";

grant delete on table "public"."year_param" to "authenticated";

grant insert on table "public"."year_param" to "authenticated";

grant references on table "public"."year_param" to "authenticated";

grant select on table "public"."year_param" to "authenticated";

grant trigger on table "public"."year_param" to "authenticated";

grant truncate on table "public"."year_param" to "authenticated";

grant update on table "public"."year_param" to "authenticated";

grant delete on table "public"."year_param" to "service_role";

grant insert on table "public"."year_param" to "service_role";

grant references on table "public"."year_param" to "service_role";

grant select on table "public"."year_param" to "service_role";

grant trigger on table "public"."year_param" to "service_role";

grant truncate on table "public"."year_param" to "service_role";

grant update on table "public"."year_param" to "service_role";


  create policy "Enable read access for all users"
  on "public"."catch_returns_staging_table"
  as permissive
  for select
  to public
using (true);




