CREATE VIEW public.view_secrep_membername_catchreturns_count_operational AS
WITH MemberStats AS (
    SELECT 
        m.member_name, 
        m.cr_name,
        COUNT(rcs.id) AS num_booked
    FROM public.members m
    INNER JOIN public.reservations_confirmed_staging rcs ON m.cr_name = rcs.cr_name
    -- CURRENT_DATE is standard in Postgres
    WHERE rcs.date < CURRENT_DATE
    GROUP BY m.member_name, m.cr_name
),
ReturnStats AS (
    SELECT 
        rod_name, 
        COUNT(*) AS total_returns
    FROM public.catch_returns_staging_table
    GROUP BY rod_name
)
SELECT 
    ms.member_name, 
    ms.num_booked, 
    COALESCE(rs.total_returns, 0) AS catch_returns,
    (ms.num_booked - COALESCE(rs.total_returns, 0)) AS variance
FROM MemberStats ms
LEFT JOIN ReturnStats rs ON ms.cr_name = rs.rod_name
-- In Postgres, Views can store an ORDER BY clause, but it is often ignored
-- by the query optimizer unless specifically called.
ORDER BY variance DESC, num_booked DESC;

CREATE TABLE "public"."report_versions" (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    report_version text,
    report_year text,
    changes_txt text,
    creation_date date,
    report_type text
);
alter table "public"."report_versions" enable row level security;
