ALTER TABLE private.members 
ADD CONSTRAINT unique_member UNIQUE (cr_name, year_of_membership);

CREATE TABLE public.reservations_confirmed (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"date" date NOT NULL,
	beats_id int4 not null,
	members_id int4 not null,
	CONSTRAINT reservations_confirmed_pkey PRIMARY KEY (id),
	CONSTRAINT uq_reservation_confirmed_date_member_beat UNIQUE (date, members_id, beats_id)
);
CREATE INDEX idx_reservations_confirmed_date ON public.reservations_confirmed USING btree (date);
CREATE INDEX idx_reservations_confirmed_beat ON public.reservations_confirmed USING btree (beats_id);
create index idx_reservations_confirmed_member on public.reservations_confirmed using btree (members_id);
ALTER TABLE public.reservations_confirmed ENABLE ROW LEVEL SECURITY;

-- Table Policies

CREATE POLICY "Allow public read access" ON public.reservations_confirmed
 AS PERMISSIVE
 FOR SELECT
 TO anon
 USING (true);

CREATE UNIQUE INDEX uq_catch_returns_member_date_only_if_not_guest
ON public.catch_returns (member_name, catch_date)
WHERE guest = false;

CREATE OR REPLACE FUNCTION private.append_reservations_from_res_conf_staging(target_year INT) -- Changed to INT
RETURNS void AS $$
BEGIN
    -- Sync Reservations utilizing the integer target_year parameter
    INSERT INTO public.reservations_confirmed ("date", members_id, beats_id)
    SELECT rcs.date, m.id, b.id 
    FROM public.reservations_confirmed_staging rcs 
    INNER JOIN private.members m ON rcs.cr_name = m.cr_name 
    INNER JOIN reservation_beats b ON rcs.resource = b.beat 
    WHERE m.year_of_membership = target_year  -- Now comparing INT = INT
    ON CONFLICT ON CONSTRAINT uq_reservation_confirmed_date_member_beat DO NOTHING;

    -- Optional: Clear staging records if desired after processing
    -- TRUNCATE TABLE public.reservations_confirmed_staging;

END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION private.append_catch_returns_from_cr_staging_table()
RETURNS void AS $$
BEGIN
    INSERT INTO public.catch_returns (
        member_name, 
        catch_date, 
        brown_trout, 
        brown_trout_killed, 
        grayling, 
        rainbow_trout, 
        other_species, 
        guest, 
        beats_id, 
        dnf
    )
    SELECT 
        crst.rod_name, 
        crst.catch_date, 
        crst.brown_trout_released, 
        crst.brown_trout_retained, 
        crst.grayling, 
        crst.rainbow_trout, 
        crst.other_species, 
        crst.guest, 
        b.id, 
        crst.dnf
    FROM public.catch_returns_staging_table crst
    INNER JOIN public.beats b ON crst.beat = b.beat
    -- Matches the exact columns and WHERE clause of your partial index:
    ON CONFLICT (member_name, catch_date) WHERE (guest = false) DO NOTHING; 

END;
$$ LANGUAGE plpgsql SECURITY DEFINER;